
services:
  db:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    container_name: auth-service
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./auth-service:/app

  post-service:
    build:
      context: ./post-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    container_name: post-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - ./post-service:/app

  user-service:
    build:
      context: ./user-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    container_name: user-service
    ports:
      - "5002:5000"
    depends_on:
      - db
    volumes:
      - ./user-service:/app

  data-service:
    build:
      context: ./data-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    container_name: data-service
    ports:
      - "5003:5000"
    depends_on:
      - db
    volumes:
      - ./data-service:/app

  interaction-service:
    build:
      context: ./interaction-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    container_name: interaction-service
    ports:
      - "5004:5000"
    depends_on:
      - db
    volumes:
      - ./interaction-service:/app

volumes:
  pgdata:
